version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - repo
    - repo1
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'tekton-multi-repo-e2e-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'Multi-repo-1-{{timestamp}}'
      source_repo_url: 'https://github.com/skaegi/hello-containers'
      type: clone
      has_issues: false
      enable_traceability: true
  repo1:
    service_id: githubpublic
    parameters:
      repo_name: 'Multi-repo-2-{{timestamp}}'
      source_repo_url: 'https://github.com/skaegi/hello-containers'
      type: clone
      has_issues: false
      enable_traceability: true
  repo2:
    service_id: githubpublic
    parameters:
      repo_name: 'Multi-repo-3-{{timestamp}}'
      source_repo_url: 'https://github.com/skaegi/hello-containers'
      type: clone
      has_issues: false
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          REPOSITORY: '{{services.repo.parameters.source_repo_url}}'
          REVISION: master
        execute: true
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
