apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: slow-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: slow-pipeline-run-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: slow-pipeline
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: slow-listener
spec:
  triggers:
    - bindings: []
      template:
        name: slow-pipeline-template
