apiVersion: v1
kind: TriggerTemplate
metadata:
  name: maven-template
spec:
  params:
    - name: API_KEY
      description: Used to fetch git token from toolchain integration, for cloning repos
    - name: ibmcloud-api
      default: https://test.cloud.ibm.com
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: maven-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: PipelineRun
      metadata:
        generateName: maven-run-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: maven
        params:
          - name: API_KEY
            value: $(params.API_KEY)
          - name: ibmcloud-api
            value: $(params.API)
        workspaces:
          - name: maven-ws
            persistentVolumeClaim:
              claimName: maven-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: maven-binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: maven-listener
spec:
  triggers:
    - binding:
        name: maven-binding
      template:
        name: maven-template
