apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: echo1
      description: echo property 1
    - name: echo2
      description: echo property 2
    - name: pull-secret
      description: pull-secret
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-pipeline-run-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: sample-pipeline
        params:
          - name: echo1
            value: $(params.echo1)
          - name: echo2
            value: $(params.echo2)
          - name: pull-secret
            value: $(params.pull-secret)
      podTemplate:
        imagePullSecrets:
          - name: pull-icr-secret
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-cluster-secret
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
