apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: echo1
      description: echo property 1
    - name: echo2
      description: echo property 2
    - name: pull-secret
      description: pull-secret
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: >-
          eyJhdXRocyI6eyJ1cy5pY3IuaW8iOnsidXNlcm5hbWUiOiJpYW1hcGlrZXkiLCJwYXNzd29yZCI6ImxSWDBTd0htcGpLMWg0eGYwYjVoTVlyNWNaTWswYkVEaUh3b3EtNmtUTWVxIiwiZW1haWwiOiJicmlhbi5nbGVlc29uQGllLmlibS5jb20iLCJhdXRoIjoiYVdGdFlYQnBhMlY1T214U1dEQlRkMGh0Y0dwTE1XZzBlR1l3WWpWb1RWbHlOV05hVFdzd1lrVkVhVWgzYjNFdE5tdFVUV1Z4In19fQ==
      metadata:
        name: image-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-pipeline-run-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: sample-pipeline
        params:
          - name: echo1
            value: $(params.echo1)
          - name: echo2
            value: $(params.echo2)
          - name: pull-secret
            value: $(params.pull-secret)
      podTemplate:
        imagePullSecrets:
          - name: image-pull-secret
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-bg-secret
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
