apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  workspaces:
    - name: pipeline-ws
  params:
    - name: API_KEY
      description: api key
    - name: API
      description: api URL
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: https://github.com/briangleeson/KEEP-pipeline-tests-resources
        - name: branch
          value: echo-secure
        - name: apikey
          value: $(params.API_KEY)
        - name:  ibmcloud-api
          value: $(params.API)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: task1
      runAfter: [clone-repo]
      taskRef:
        name: task1
      workspaces:
        - name: output
          workspace: pipeline-ws
