apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: https://github.com/briangleeson/simple-maven-project-with-tests
        - name: branch
          value: master
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: maven-task
      taskRef:
        name: maven-task
