apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
    - name: BRANCH
      default: default
  tasks:
    - name: task1
      taskRef:
        name: task1
      params:
        - name: BRANCH
          value: $(params.BRANCH)
