apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
    - name: ibmcloud-api
      default: https://cloud.ibm.com
  workspaces:
    - name: npm-ws
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: https://github.com/briangleeson/continuous-delivery-node-sdk
        - name: branch
          value: networking
        - name: ibmcloud-apikey-secret-key
          value: API_KEY
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
      workspaces:
        - name: output
          workspace: npm-ws
    - name: task1
      taskRef:
        name: task1
      runAfter:
        - clone-repo
      workspaces:
        - name: output
          workspace: npm-ws
