apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven
spec:
  workspaces:
    - name: maven-ws
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: https://github.com/briangleeson/simple-maven-project-with-tests
        - name: branch
          value: networking
        - name: ibmcloud-apikey-secret-key
          value: API_KEY
        - name: ibmcloud-api
          value: https://test.cloud.ibm.com
      workspaces:
        - name: output
          workspace: maven-ws
    - name: maven-task
      taskRef:
        name: maven-task
      runAfter:
        - clone-repo
      workspaces:
        - name: output
          workspace: maven-ws
