apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
    - name: API_KEY
      description: api key
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: https://github.com/briangleeson/KEEP-pipeline-tests-resources
        - name: branch
          value: echo-secure
        - name: ibmcloud-apikey-secret-key
          value: $(params.API_KEY)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: task1
      taskRef:
        name: task1
