apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-eile-pipeline
spec:
  params:
    - name: echo1
      description: echo property 1
    - name: echo2
      description: echo property 2
    - name: pull-secret
      description: pull-secret
  tasks:
    - name: task-eile-1
      taskRef:
        name: task-eile
      params:
        - name: echo1
          value: $(params.echo1)
        - name: echo2
          value: $(params.echo2)
        - name: pull-secret
          value: $(params.pull-secret)
