apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven
spec:
  params:
    - name: API_KEY
  workspaces:
    - name: maven-ws
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: https://github.com/briangleeson/simple-maven-project-with-tests
        - name: branch
          value: master
        - name: ibmcloud-apikey-secret-key
          value: $(params.API_KEY)
      workspaces:
        - name: output
          workspace: maven-ws
    - name: maven-task
      taskRef:
        name: maven-task
