apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  params:
    - name: echo1
      description: echo property 1
    - name: echo2
      description: echo property 2
    - name: pull-secret
      description: pull-secret
  steps:
    - name: task-one-step-one
      image: us.icr.io/projects-pipeline-images/projects-pipeline-image@sha256:bab58b96b6def84db1fd57fffa74a79865107b5373b4109cafdd3121f001a920
      imagePullPolicy: Always
      env:
        - name: ECHO1
          value: $(params.echo1)
        - name: ECHO2
          value: $(params.echo2)
        - name: pull-secret
          value: $(params.pull-secret)
      command: ["bash", "-c"]
      args:
        - |
          #!/usr/bin/env bash
          echo "=======================";
          echo "echo1: ${ECHO1}";
          echo "echo2: ${ECHO2}";
          echo "=======================";
          echo "image: us.icr.io/projects-pipeline-images/projects-pipeline-image@sha256:bab58b96b6def84db1fd57fffa74a79865107b5373b4109cafdd3121f001a920"
