apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  params:
    - name: echo1
      description: echo property 1
    - name: echo2
      description: echo property 2
    - name: pull-secret
      description: pull-secret
  steps:
    - name: task-one-step-one
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image
      env:
        - name: ECHO1
          value: $(params.echo1)
        - name: ECHO2
          value: $(params.echo2)
        - name: pull-secret
          value: $(params.pull-secret)
      command: ["bash", "-c"]
      args:
        - |
          #!/usr/bin/env bash
          echo "=======================";
          echo "echo1: ${ECHO1}";
          echo "echo2: ${ECHO2}";
          echo "=======================";
          sleep 600
          echo "image: icr.io/continuous-delivery/pipeline/pipeline-base-image"
