apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: alpine
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "Greenwell Site - Health Check";
          echo "Using https://github.com/ziheng-c/greenwell-tekton.git";
          echo "=======================";
          sleep 10;
          apt-get -qq update; apt-get -qq -y install curl;
          sleep 10;
          alive=$(curl -k https://greenwell-app.eu-de.mybluemix.net/health);
          if [ "$alive" == "200 - Healthy" ];
          then echo "TEST PASS - 200"; exit 0;
          else echo "TEST FAIL - $alive"; exit 1;
          fi
