apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  workspaces:
  - name: output
    mountPath: /output
  steps:
    - name: task-one-step-one
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.66
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "Test npm installs";
          echo "=======================";
          cd output;
          ls -a;
          echo "=======================";
          # npm install -g npm@10.3.0 && echo "Done 10.3.0";
          npm version;
          echo "=======================";
          npm install -g npm@10.9.0 && echo "Done 10.9.0";
          npm version;
          echo "=======================";
          echo "Its over";
          echo "=======================";
