apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mavenTask
spec:
  steps:
    - name: maven-step
      image: 3.8.3-openjdk-17-slim
      command: ["bash", "-c"]
      args:
        - sh 'mvn -B -ntp -Dmaven.test.failure.ignore verify'
