apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  workspaces:
    - name: output
      mountPath: /artifacts
  steps:
    - name: task-one-step-one
      image: centos
      envFrom:
        - configMapRef:
            name: environment-properties
        - secretRef:
            name: secure-properties
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "secure1 = ${secure1}";
          echo "=======================";
          echo $(ls -a);
          echo "=======================";
          echo $(ls -a ./artifacts);
          cat ./artifacts/.tekton/riti-logs.txt;
          echo "=======================";
          echo $(ls -a ./workspace);
          echo "=======================";
          
