apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: centos
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "IBM Cloud - Networking debug";
          echo "=======================";
          echo "Installing networking tools";
          sudo apt install net-tools
          echo "=======================";
          echo "[DEBUG] Netstat";
          netstat -tulpn   | grep :9999
          echo "=======================";
          echo "[DEBUG] LSOF";
          lsof -> lsof -i :9999
          echo "=======================";
          echo "[DEBUG] ping";
          ping -c 10 localhost
          echo "=======================";
          echo "COMPLETED";
