apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - apt-get -qq update;
          echo "apt-get update complete";
          apt-get -qq -y install apt-utils 2> >( grep -v 'debconf: delaying package configuration, since apt-utils is not installed' >&2 );
          echo "apt-utils install complete";
          apt-get -qq -y --no-install-recommends install curl;
          echo "curl install complete";
          echo "=======================";
          echo "Greenwell Site - Health Check";
          echo "Using https://github.com/ziheng-c/greenwell-tekton.git";
          alive=$(curl https://greenwell-app.eu-de.mybluemix.net/health);
          if [ "$alive" == "200 - Healthy" ];
          then echo "TEST PASS - 200"; exit 0;
          else echo "TEST FAIL - $alive"; exit 1;
          fi
