apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-task
spec:
  workspaces:
  - name: output
    mountPath: /output
  steps:
    - name: maven-step
      image: maven:3.8.3-openjdk-17-slim
      command: ["bash", "-c"]
      args:
        - |
          echo "====="
          echo "Pre-test install"
          apt-get update && apt-get install -y bash curl iputils-ping net-tools
          echo "====="
          echo "Pre-test checks"
          echo "hostname"
          hostname;
          echo "whoami"
          whoami;
          echo "ping"
          ping localhost -c 5
          ping 127.0.0.1 -c 5
          ping 0.0.0.0 -c 5
          echo "====="
          cd output
          mvn -B -ntp -Dmaven.test.failure.ignore verify
          echo "====="
          echo "Tests complete"
