apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: centos
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "BRANCH: $BRANCH";
          echo "=======================";
          get_env BRANCH;
          echo "=======================";
          exit 0;
