apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  params:
    - name: BRANCH
  steps:
    - name: task-one-step-one
      env:
        - name: BRANCH
          value: $(params.BRANCH)
        - name: ECHO2
          value: $(params.BRANCH)
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "BRANCH - $BRANCH";
          echo "=======================";
          exit 0;
