apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-task
spec:
  workspaces:
  - name: output
    mountPath: /output
  steps:
    - name: maven-step
      image: maven:3.8.3-openjdk-17-slim
      command: ["bash", "-c"]
      args:
        - |
          ls -a
          echo "====="
          cd output
          ls -a
          echo "====="
          cd simple-maven-project-with-tests
          ls -a
          echo "====="
          mvn -B -ntp -Dmaven.test.failure.ignore verify
