apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: centos
      envFrom:
        - configMapRef:
            name: environment-properties
        - secretRef:
            name: secure-properties
      command: ["bash", "-c"]
      args:
        - echo "=======================";
          echo "secure1 = ${secure1}";
          echo "=======================";
          ls -a
          echo "=======================";
          echo $(ls -a)
          echo "=======================";
          
